services:
  - type: web
    name: EventPlaN
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATA_DIR
        value: /var/data
    disk:
      name: eventplan-data
      mountPath: /var/data
      sizeGB: 1
